name: Build

on:
  release:
    types: [published, created, released]
jobs:
  build_matrix:
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest']
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    # - name: Build
    #   run: cargo build --verbose --release
    - name: Name
      run: |
        echo $AUTHOR
      env:
        AUTHOR: ${{ github.event.release.author.email }}
      
