name: Build

on:
  release:
    types: [published]
jobs:
  build_matrix:
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest']
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    # - name: Build
    #   run: cargo build --verbose --release
    - name: Name
      run: echo ${{ github.event.release.author.email }}
