name: Build

on:
  release:
    types: [released]
jobs:
  build_matrix:
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest']
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    # - name: Build
    #   run: cargo build --verbose --release
    - name: Release
      run: |
        bash scripts/release.sh
      env:
        OWNER: ${{ github.event.release.author.login }}
        RELEASE: ${{ github.event.release.id }}
        REPO: ${{ github.event.repository.name }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
